### ISSUE TITLE
Photopmap/since - wants Unix timestamp

### ISSUE THREAD

**Issue by si-the-pie** [cyclestreets/mobileweb2022#15] opened 2021-01-12 15:38 UTC
# Photomap / since
Select any year in the `Since` field to get this screenshot from iphone 7 / Firefox at https://m.cyclestreets.net/photomap:since=NaN/#17.25/52.199272/0.147761

![IMG_755D0215AC4E-1](https://user-images.githubusercontent.com/361987/104334600-78298700-54ea-11eb-9556-47f64444e9ac.jpeg)

# Desktop
Selecting the same link on a laptop doesn't immediately give the failure, but selecting a since date does reproduce the problem on subsequent occasions.

**Comment by mvl22** [comment] 2021-01-12 16:13
Hmm, that's odd, as the select control is using the `data-yearly-since-unixtime` (as per Bikedata) which generates Unixtimes as the values. (Use the Console > Inspect to see the underlying values.)

Could you give a specific reproduce case sequence for desktop, as I can't reproduce this at present.

**Comment by si-the-pie** [comment] 2021-01-12 22:41
On the desktop device open a new private window in **Safari** or **Firefox** and go to:

 https://m.cyclestreets.net/photomap

Select e.g. 2008 (or any year) and the modal dialog appears, taking you back to 1995 :-)

However it does work marvellously on Chrome - nice feature.

**Comment by mvl22** [comment] 2021-01-12 23:08
OK, thanks.

Yes, I can see that in those browsers it creates:

```
<option value="NaN">2021</option>
<option value="NaN">2020</option>
etc.
```

as shown in the inspector.

It will be an error therefore in the underlying layerviewer library at:

https://github.com/cyclestreets/Mapboxgljs.LayerViewer/blob/master/src/layerviewer.js#L1178-L1191

**Comment by mvl22** [comment] 2021-01-22 18:37
The fix is change the new Date section to:

`new Date (year, 1, 1)`

**Comment by mvl22** [comment] 2021-01-22 18:43
Fixed in https://github.com/cyclestreets/Mapboxgljs.LayerViewer/commit/0a21100a0267134d0fa1fc6a2841bd90b803354b.

**Closed as completed by mvl22** 2021-01-22 18:43 UTC
